"""
Django settings for invoice_sys project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


AUTH_USER_MODEL = 'accounts.User'

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'clients',
    'common',
    'invoices',
    'payments',
    'products',
    'auditlog',
    'dashboard',
    'rest_framework',
    'rest_framework_simplejwt',
    'graphene_django',
    'drf_spectacular',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        
    ),
     'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',  # دي اللي بتفتح الفورم في المتصفح
    ]
    ,
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,  # in all apis such as products, clients, invoices
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
        "rest_framework.filters.OrderingFilter",
        "rest_framework.filters.SearchFilter",]
        ,
     'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '10/day',            #10/day
        'user': '1000/day',           #1000/day
        'login': '5/min',        # 5/hour مسموح بـ 5 محاولات فقط كل ساعة لكل IP
    },
'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}
        
        # إعدادات اختيارية للـ Swagger
SPECTACULAR_SETTINGS = {
    'TITLE': 'Invoice System API',
    'DESCRIPTION': 'Documentation for Invoices and Clients Management System',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
]

ROOT_URLCONF = 'invoice_sys.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],  # هنا بنقول لدجانجو يدور في مجلد templates اللي جوة المشروع
        'APP_DIRS': True,                  # ده بيخلي Django كمان يدور في templates بتاعة كل app
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'invoice_sys.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# invoice_sys/settings.py



#}
#import dj_database_url
#from decouple import config
#from pathlib import Path
#DATABASES = {
#    'default': dj_database_url.config(
#        default=config('DATABASE_URL', default=f"sqlite:///{BASE_DIR/'db.sqlite3'}")
#    )
#}
#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

'''STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
'''
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # مجلدك فيه register.html
STATIC_ROOT = BASE_DIR / 'staticfiles'    # للـ collectstatic

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
#______________

import os

SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key")
DEBUG = True
#DEBUG = os.environ.get("DEBUG", "True") == "True"
ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# Database configuration
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get("POSTGRES_DB", "invoice_db"),
        'USER': os.environ.get("POSTGRES_USER", "invoice_user"),
        'PASSWORD': os.environ.get("POSTGRES_PASSWORD", "strongpassword"),
        'HOST': 'db',
        'PORT': 5432,
    }
}

# Redis / Celery example
REDIS_HOST = os.environ.get("REDIS_HOST", "redis")
REDIS_PORT = int(os.environ.get("REDIS_PORT", 6379))
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"
CELERY_RESULT_BACKEND = f"redis://{REDIS_HOST}:{REDIS_PORT}/0"

# Security (تشتغل بس في production)
CSRF_COOKIE_SECURE = not DEBUG
SESSION_COOKIE_SECURE = not DEBUG
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = "DENY"

# Auth redirects
LOGIN_REDIRECT_URL = '/invoices/'
LOGIN_URL = '/accounts/login/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

STATICFILES_STORAGE = "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"

import os
from pathlib import Path
from dotenv import load_dotenv

# 1. تحديد مسار المشروع الأساسي
# (تأكد أن هذا السطر موجود مرة واحدة فقط في أعلى الملف)
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. تحميل الملف بناءً على البيئة (Development أو Production)
# نقرأ المتغير DJANGO_ENV من الـ Docker Compose
env_mode = os.getenv('DJANGO_ENV', 'development')
env_path = BASE_DIR / '.env.production' if env_mode == 'production' else BASE_DIR / '.env'

# تنفيذ عملية التحميل من الملف المختار
load_dotenv(dotenv_path=env_path)

# 3. إعدادات بريد جوجل (SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# 4. استخراج القيم الحساسة من الملف الذي تم تحميله
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# 5. إعداد البريد المرسل (الاسم الذي يظهر للمستلم)
# نستخدم f-string لدمج اسم النظام مع الإيميل المستخرج
DEFAULT_FROM_EMAIL = f"Invoice System <{EMAIL_HOST_USER}>"
SERVER_EMAIL = EMAIL_HOST_USER
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://redis:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"

CSRF_TRUSTED_ORIGINS = ['http://localhost:8000', 'http://127.0.0.1:8000']

GRAPHENE = {
    "SCHEMA": "invoice_sys.schema.schema" 
}

from django.core.cache import cache
import pytest

@pytest.mark.django_db
class TestLoginThrottle:
    def setup_method(self):
        cache.clear() # دي بتصفر العداد قبل كل تست
    # ... باقي التست