# Generated by Django 4.2.27 on 2026-02-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="invoice",
            options={"ordering": ["-date", "-id"]},
        ),
        migrations.AlterField(
            model_name="invoice",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="due_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("paid", "Paid"),
                    ("unpaid", "Unpaid"),
                    ("overdue", "Overdue"),
                ],
                db_index=True,
                default="unpaid",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=0, max_digits=10
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["client", "date"], name="invoices_in_client__f246d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoice",
            index=models.Index(
                fields=["status", "date"], name="invoices_in_status_205b83_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="invoiceitem",
            index=models.Index(
                fields=["invoice", "product"], name="invoices_in_invoice_9d954a_idx"
            ),
        ),
    ]
